### ISSUE TITLE
Why don't enemy ?

### ISSUE THREAD

**Issue by WormerKing** [asanadam12/FireDungeons#1]
Why FireDungeons game in not enemy ?
And sword+left click in error:
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
FireDungeons.py:27: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  Bar = pg.Rect(58, 16, health*1.2, 18)
FireDungeons.py:28: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  Bar2 = pg.Rect(58, 16, health*1.2, 6)
Traceback (most recent call last):
  File "FireDungeons.py", line 154, in <module>
    g.run()
  File "FireDungeons.py", line 73, in run
    self.events()
  File "FireDungeons.py", line 134, in events
    pg.mixer.Sound("assets/sounds/slash.wav").play()
pygame.error: Unable to open file 'assets/sounds/slash.wav'

**Comment by asanadam12** [comment]
im gonna fix this :wink:

**Comment by asanadam12** [comment]
im developing pyroman too im adding water physics to pyro man hehe
